"""empty message

Revision ID: 2f56f8a33f8
Revises: None
Create Date: 2014-11-26 03:53:21.033877

"""

# revision identifiers, used by Alembic.
revision = '2f56f8a33f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
